spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

azure:
  eventhub:
    connection-string: ${AZURE_EVENTHUB_CONNECTION_STRING}
    sender-hub-name: ${AZURE_EVENTHUB_SENDER_NAME}
    result-hub-name: ${AZURE_EVENTHUB_RESULT_NAME}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
  api-docs:
    path: /api-docs